#!/usr/bin/env python3
"""Line-coverage gate for compute_budget.py's own test suite.

Stdlib only (trace + dis.findlinestarts()) - no pip in the vendored
interpreter, so coverage.py isn't an option. Mirrors this repo's vitest
coverage gate in spirit: run the tests, measure line coverage, fail below a
threshold. Ratchet the threshold up only, per the repo's testing
conventions - never lower it to make a change pass.

Usage: python3 coverage_check.py
"""
import ast
import dis
import sys
import trace
import unittest
from pathlib import Path

THRESHOLD = 100.0  # percent - ratchet up only, never down (see module docstring)

HERE = Path(__file__).resolve().parent
TARGET = HERE / "compute_budget.py"


def executable_lines(path: Path) -> set[int]:
    """Lines the compiler actually emits bytecode for - functions, module
    level, comprehensions - via dis.findlinestarts() on every nested code
    object. Portable across Python versions (unlike co_lines(), 3.10+
    only) - the vendored interpreter is 3.12, but a contributor's system
    python3 may be older."""
    code = compile(path.read_text(), str(path), "exec")
    lines: set[int] = set()

    def walk(co) -> None:
        for _offset, ln in dis.findlinestarts(co):
            if ln > 0:  # 3.11+ emits a synthetic line-0 marker for some
                lines.add(ln)  # generated bytecode; never a real source line.
        for const in co.co_consts:
            if hasattr(const, "co_consts"):
                walk(const)

    walk(code)
    return lines


def main_guard_body_lines(path: Path) -> set[int]:
    """Line numbers inside the body of `if __name__ == "__main__":` - real
    code that only executes when this script runs as a subprocess (which
    TestScriptEntryPoint in test_compute_budget.py does exercise), so this
    in-process line tracer can never see it hit. Detected via ast rather
    than a hardcoded line count, so the exemption tracks edits to that
    block automatically instead of silently under- or over-counting."""
    tree = ast.parse(path.read_text(), filename=str(path))
    lines: set[int] = set()
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.If)
            and isinstance(node.test, ast.Compare)
            and isinstance(node.test.left, ast.Name)
            and node.test.left.id == "__name__"
        ):
            for stmt in node.body:
                for sub in ast.walk(stmt):
                    if hasattr(sub, "lineno"):
                        lines.add(sub.lineno)
    return lines


def main() -> None:
    # Discovery has to happen *inside* runfunc too, not before it - it's what
    # first imports compute_budget.py, and everything module-level (imports,
    # `def` lines, class bodies) only executes once, at that import. Tracing
    # only the runner.run() call would miss all of it.
    def discover_and_run():
        suite = unittest.defaultTestLoader.discover(str(HERE), pattern="test_*.py")
        return unittest.TextTestRunner(verbosity=1).run(suite)

    tracer = trace.Trace(count=True, trace=False)
    result = tracer.runfunc(discover_and_run)

    if not result.wasSuccessful():
        print("Tests failed - fix them before coverage means anything.", file=sys.stderr)
        sys.exit(1)

    counts = tracer.results().counts  # {(filename, lineno): hit_count}
    target = str(TARGET)
    covered = {ln for (fn, ln), n in counts.items() if Path(fn).resolve() == TARGET and n > 0 or fn == target and n > 0}

    total = executable_lines(TARGET) - main_guard_body_lines(TARGET)
    hit = total & covered
    missed = sorted(total - covered)
    pct = 100.0 * len(hit) / len(total) if total else 100.0

    print(f"\nLine coverage for {TARGET.name}: {pct:.1f}% ({len(hit)}/{len(total)})")
    if missed:
        print(f"Uncovered lines: {', '.join(map(str, missed))}")

    if pct + 1e-9 < THRESHOLD:
        print(f"ERROR: coverage {pct:.1f}% is below the {THRESHOLD}% threshold", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
